### ISSUE TITLE
Ever found a solution to this?

### ISSUE THREAD

**Issue by dcristolovean** [SuperTango/InputAccessoryView#1]
I know this is old, but have you ever found a solution to this?

**Comment by SuperTango** [comment]
Unfortunately, I don't think so. I think I ended up changing the app structure to remove the UIPageViewController.  Sorry.

**Comment by dcristolovean** [comment]
I found the solution after asking you, the only thing that needs to be done is when you select one of your pages somehow and you call the setViewControllers([controllers[0].....) , after that, you just need to do a controllers[0].becomeFirstResponder().
And that's it, works like magic, like it does without the page controller.

**Comment by SuperTango** [comment]
Great! Can you put that answer in the SO question (https://stackoverflow.com/questions/51320530/inputaccessoryview-inside-a-uipageviewcontroller-doesnt-show-by-default) and I'll accept it.

**Comment by dcristolovean** [comment]
sure.

**Comment by SuperTango** [comment]
Hm.  I actually tried your solution and it doesn't work unless i stick the `becomeFirstResponder` call inside a `DispatchQueue.main.async` block like this: 

    func setViewController() {
        let newViewController = self.orderedViewControllers[2]
        setViewControllers([newViewController],
                           direction: .forward,
                           animated: true,
                           completion: { (finished: Bool) in
                            DispatchQueue.main.async {
                                x.becomeFirstResponder()
                            }   
        })
    }

Also, this doesn't work when the user scrolls between view controllers. 

Now i'm interested in this issue again.  I'm working ATM, but will look more later. Thanks for bringing it up though.

**Comment by dcristolovean** [comment]
I suppose "x" is newViewController.  I didn't do it in the completion block, just right after set.
I have something like this:

`if currentPage < button.tag - 1 {
            pageVC.setViewControllers([controllers![button.tag - 1]], direction: .forward, animated: false, completion: nil)
        }
        else {
            pageVC.setViewControllers([controllers![button.tag - 1]], direction: .reverse, animated: false, completion: nil)
        }
        controllers![button.tag - 1].becomeFirstResponder()
`
Indeed, it doesn't work while swipping, even if I put the becomeFirstResponder() call in the 2 methods that return the next/previous view controller.
If you find a fix for that, don't forget to write here :)
